services:
  web:
    container_name: "django-otp-auth"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: >
      sh -c "python manage.py migrate --noinput
      && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    container_name: "django-otp-auth-db"
    restart: always
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data/
    expose:
      - 5432

volumes:
  pg_data:
